name: Swift Vapor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Swift Vapor Project
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Swift
        uses: swiftaction/setup-swift@v1
        with:
          swift-version: '5.7'  #

      - name: Install dependencies
        run: |
          swift package resolve

      - name: Run Tests
        run: |
          swift test